In [1]:
import pandas as pd

In [2]:
from google.colab import files

uploaded = files.upload()

Saving student-por-selected-columns.csv to student-por-selected-columns.csv

In [3]:
df = pd.read_csv("student-por-selected-columns.csv")

In [4]:
df.head()

   school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob  Fjob
0     NaN  NaN  NaN      NaN      NaN      NaN   NaN   NaN   NaN   NaN
1     NaN  NaN  NaN      NaN      NaN      NaN   NaN   NaN   NaN   NaN
2     NaN  NaN  NaN      NaN      NaN      NaN   NaN   NaN   NaN   NaN
3     NaN  NaN  NaN      NaN      NaN      NaN   NaN   NaN   NaN   NaN
4     NaN  NaN  NaN      NaN      NaN      NaN   NaN   NaN   NaN   NaN

In [5]:
print(df.columns)

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   school   0 non-null      float64
 1   sex      0 non-null      float64
 2   age      0 non-null      float64
 3   address  0 non-null      float64
 4   famsize  0 non-null      float64
 5   Pstatus  0 non-null      float64
 6   Medu     0 non-null      float64
 7   Fedu     0 non-null      float64
 8   Mjob     0 non-null      float64
 9   Fjob     0 non-null      float64
dtypes: float64(10)
memory usage: 10.1 KB

In [7]:
df.shape

(127, 10)

In [8]:
df.isnull().sum()

school     127
sex        127
age        127
address    127
famsize    127
Pstatus    127
Medu       127
Fedu       127
Mjob       127
Fjob       127
dtype: int64

In [9]:
age = 17

if age >= 18:
    print("Adult")
else:
    print("Minor")

Minor

In [10]:
def age_category(age):
    if age >= 18:
        return "Adult"
    else:
        return "Minor"

df["Age_Category"] = df["age"].apply(age_category)

In [11]:
df[["age", "Age_Category"]].head()

   age Age_Category
0  NaN        Minor
1  NaN        Minor
2  NaN        Minor
3  NaN        Minor
4  NaN        Minor

In [12]:
def age_group(age):
    if age <= 16:
        return "Young"
    elif age <= 18:
        return "Teen"
    else:
        return "Older"

df["Age_Group"] = df["age"].apply(age_group)

In [13]:
df[["age", "Age_Group"]].head()

   age Age_Group
0  NaN     Older
1  NaN     Older
2  NaN     Older
3  NaN     Older
4  NaN     Older

In [14]:
def student_category(age, medu):
    if age >= 18 and medu >= 3:
        return "Category A"
    else:
        return "Category B"

df["Student_Category"] = df.apply(
    lambda row: student_category(row["age"], row["Medu"]),
    axis=1
)

In [15]:
def location_category(address):
    if address == "U" or address == "R":
        return "Known Location"
    else:
        return "Other"

df["Location_Category"] = df["address"].apply(location_category)

In [16]:
def mother_job_category(job):
    if job == "teacher":
        return "Education"
    elif job == "health":
        return "Healthcare"
    else:
        return "Other"

df["Mother_Job_Category"] = df["Mjob"].apply(mother_job_category)

In [17]:
def education_comparison(medu, fedu):
    if medu > fedu:
        return "Mother education higher"
    elif medu < fedu:
        return "Father education higher"
    else:
        return "Same education level"

df["Parent_Education"] = df.apply(
    lambda row: education_comparison(row["Medu"], row["Fedu"]),
    axis=1
)

In [18]:
df.head(10)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,Age_Category,Age_Group,Student_Category,Location_Category,Mother_Job_Category,Parent_Education
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor,Older,Category B,Other,Other,Same education level
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor,Older,Category B,Other,Other,Same education level
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor,Older,Category B,Other,Other,Same education level
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor,Older,Category B,Other,Other,Same education level
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor,Older,Category B,Other,Other,Same education level
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor,Older,Category B,Other,Other,Same education level
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor,Older,Category B,Other,Other,Same education level
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor,Older,Category B,Other,Other,Same education level
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor,Older,Category B,Other,Other,Same education level
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Minor,Older,Category B,Other,Other,Same education level